"""Initial migration

Revision ID: 840d452e777f
Revises: 
Create Date: 2025-11-02 02:59:43.689530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840d452e777f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_address_address', 'addresses', ['address'], unique=False)
    op.create_index('idx_address_latitude', 'addresses', ['latitude'], unique=False)
    op.create_index('idx_address_longitude', 'addresses', ['longitude'], unique=False)
    op.create_table('domain',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['domain.id'], name='fk_domain_parent_id__domain_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_domain_name', 'domain', ['name'], unique=False)
    op.create_table('enterprises',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address_id', sa.BigInteger(), nullable=False),
    sa.Column('domain_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], name='fk_enterprise_domain_id__domain_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_enterprise_name', 'enterprises', ['name'], unique=False)
    op.create_table('phones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('enterprise_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phones')
    op.drop_index('idx_enterprise_name', table_name='enterprises')
    op.drop_table('enterprises')
    op.drop_index('idx_domain_name', table_name='domain')
    op.drop_table('domain')
    op.drop_index('idx_address_longitude', table_name='addresses')
    op.drop_index('idx_address_latitude', table_name='addresses')
    op.drop_index('idx_address_address', table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
